export const cuisineTypes = [
  'Belarussian cuisine',
  'Brazilian cuisine',
  'Chinese cuisine',
  'Greek cuisine',
  'Italian cuisine',
  'Indian cuisine',
  'Japanese cuisine',
  'Korean cuisine',
  'Lebanese cuisine',
  'Mexican cuisine',
  'Mexican french',
  'Mediterranean cuisine',
  'Moroccan cuisine',
  'Russian cuisine',
  'Spanish cuisine',
  'Thai cuisine',
  'Turkish cuisine',
  'Vietnamese cuisine',
  'Other',
];
