export const cuisineTypes = [
  'Belarussian cuisine',
  'Brazilian cuisine',
  'Chinese cuisine',
  'Greek cuisine',
  'Italian cuisine',
  'Indian cuisine',
  'Japanese cuisine',
  'Korean cuisine',
  'Lebanese cuisine',
  'Mexican cuisine',
  'Mexican french',
  'Mediterranean cuisine',
  'Moroccan cuisine',
  'Russian cuisine',
  'Spanish cuisine',
  'Thai cuisine',
  'Turkish cuisine',
  'Vietnamese cuisine',
  'Other',
];

export const localizedCuisineTypes = {
  en: [
    'Belarussian cuisine',
    'Brazilian cuisine',
    'Chinese cuisine',
    'Greek cuisine',
    'Italian cuisine',
    'Indian cuisine',
    'Japanese cuisine',
    'Korean cuisine',
    'Lebanese cuisine',
    'Mexican cuisine',
    'Mexican french',
    'Mediterranean cuisine',
    'Moroccan cuisine',
    'Russian cuisine',
    'Spanish cuisine',
    'Thai cuisine',
    'Turkish cuisine',
    'Vietnamese cuisine',
    'Other',
  ],
  ru: [
    'Белорусская кухня',
    'Бразильская кухня',
    'Китайская кухня',
    'Греческая кухня',
    'Итальянская кухня',
    'Индийская кухня',
    'Японская кухня',
    'Корейская кухня',
    'Ливанская кухня',
    'Мексиканская кухня',
    'Мексикано-французская кухня',
    'Средиземноморская кухня',
    'Марокканская кухня',
    'Русская кухня',
    'Испанская кухня',
    'Тайская кухня',
    'Турецкая кухня',
    'Вьетнамская кухня',
    'Другое',
  ],
};
