export const cuisineTypes = [
  'Lebanese cuisine',
  'Italian cuisine',
  'Greek cuisine',
  'Mexican cuisine',
  'Mexican french',
  'Chinese cuisine',
  'Indian cuisine',
  'Japanese cuisine',
  'Thai cuisine',
  'Spanish cuisine',
  'Korean cuisine',
  'Turkish cuisine',
  'Moroccan cuisine',
  'Brazilian cuisine',
  'Vietnamese cuisine',
];
