export const foodCategories = [
  'Baked goods',
  'Sweets and desserts',
  'Meat and poultry',
  'Vegetables',
  'Snacks',
  'Salads',
  'Breakfast',
  'Lunch',
  'Dinner',
  'Dessert',
  'Drinks',
  'Gluten free',
  'Lactose free',
  'Sugar free',
  'Vegan',
  'Seafood',
  'Low calories',
  'Dairy products',
  'Condiments and sauces',
];
